name: ci
on: [push, pull_request]
jobs:
  build-Linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: ./tools/autogen.sh
    - run: ./configure
    - run: make
    - run: make check

  build-Linux_clang:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - || exit 1
    - run: sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main" || exit 1
    - run: sudo apt-get update || exit 1
    - run: sudo apt-get install -y clang-11
    - run: export CC="clang-11" && ./tools/autogen.sh && ./configure USE_PTHREAD=no && make USE_PTHREAD=no && make check

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install gnu-sed automake
    - run: ./tools/autogen.sh
    - run: ./configure USE_PTHREAD=no
    - run: make
    - run: make check

